NoroffFEU/development-platforms

prometheus_toolkit.md

Opening a PR for review from Oliver

Prometheus - Case Study

---

google-platforms-case-study.md

Would like some feedback on my case-study.
Are we suppose to format the text file in a certain way? like different from what I have done, or is this fine?

Google Platforms - Case Study

---

Azure-DevOps-case-study.md

Wanted to have a look at Azure DevOps as a system, but also in comparison to the similar system GitHub.

Azure dev ops case study

---

NextJs-case-study.md

Here is my PR/Pull Request to the upstream main. Would appreciate the review of the next js case study.

Next js case study

---

case-studies/gitkraken/gitkraken-case-study.md

Release Notes:
- Documentation: Adds a case study of GitKraken, covering its history, features, strengths, weaknesses, and how to get started with it. Provides additional resources and references for further reading.
> "GitKraken, oh GitKraken,
> Your story we now tell,
> With features, strengths, and weaknesses,
> And how to use you well.
> A case study we present,
> For all the world to see,
> Your multiplatform GUI,
> Makes Git a breeze, with glee."

GitKraken case study

---

supabase-case-study.md

- Documentation: Adds a case study of Supabase, including an introduction, brief history, main features, strengths, weaknesses, comparison with Firebase, and conclusion. Includes references to various sources.
> "Supabase shines bright,
> With PostgreSQL and more in sight.
> A case study now in view,
> Thanks to this PR's crew."

Supabase case study.md

---

case-studies/Appwrite-video-case-study.md

Submitting Video Case Study About Appwrite. Requesting Review

Adds appwrite video case study

---

case-studies/appwrite/Appwrite-video-case-study.md

Changed target to upstream main.
@Fermain

Create the file containing my video case study for Appwrite.

---

package-lock.json
src/content/docs/frameworks/Remix/remix-case-study.md

This is my case study for the Remix framework.

Remix case study

---

src/content/docs/openai/DALL·E/DALL·E-case-study.md

This Pull Request includes my case study for DALL·E, formatted in Markdown. It covers features, applications, user guides, ethics discussions and comparisons to other image generating AI's. 
It aims to provide a valuable resource for developers at all levels who are interested in using or integrating DALL·E in their projects.

DALLE case study

---

src/content/docs/frameworks/Angular/angular-case-study.md

This contains the angular case study.
It should be done, but I may come back and edit some parts.

Angular case study

---

package-lock.json
src/content/docs/webdev-hosting/DigitalOcean/digitalOcean-case-study.md

This is my case study for DigitalOcean. I hope this will be a valuable addition to the library. Please let me know if I should make any changes. Thanks.

Adds DigitalOcean case study

---

src/content/docs/kotlin-multiplatform/kotlin-multiplatform-case-study.md

Hi!
Here's my case study about KMP. Please let me know if you have any feedback.

Adds Kotlin multiplatform case study

---

src/content/docs/security/captcha-case-study.md

Look into bot prevention with CAPTCHA

Captcha case study

---

src/content/docs/devtools/GraphQL/GraphQL-case-study.md

Fixes case study without frontmatter set.

Add frontmatter, fix codeblock lang

---

package-lock.json
src/content/docs/devtools/IDE/IntelliCode-case-study.md

Hey, this is my IntelliCode case study

IntelliCiode case study

---

astro.config.mjs
src/content/docs/security/imperva-case-study.md

This pull request introduces the complete case study on Imperva.
Any feedback is appreciated.
Thank you in advance for your time and insights.

Imperva case study

---

src/content/docs/databases/Redis/redis-case-study.md

This pull request adds a comprehensive case study on Redis.
The document includes:
- An Introduction to Redis and its significance in the industry.
- A Brief History outlining the milestones in Redis development.
- A section on Main Features detailing Redis’s capabilities.
- A comparison with other in-memory data stores.
- A Getting Started Guide for new users.
- Instructions for Integrating Redis with Visual Studio Code, which provides a practical guide to setting up Redis within this popular IDE.
- Case Studies and Success Stories that highlight Redis's impact.
- A Conclusion that reflects on Redis's position and future in technology.
- Comprehensive References and Additional Resources for further reading and deeper exploration of Redis.

Redis Case Study

---

src/content/docs/cms/sanity.md

I have made a case study about Sanity as a headless CMS.
Includes:
- What a headless CMS is
- Brief history
- Main features
- Comparison of headless CMS vs. traditional CMS
- I´ve looked into Crystallize as a headless eCommerce, and WordPress as a traditional CMS compared to Sanity

Sanity case study

---

src/content/docs/baas/Supabase/supabase-overview.md

This PR introduces a case study on Supabase, an open-source Firebase alternative. It explores key features, real-time capabilities, and compares it to Firebase. Ideal for front-end developers interested in BaaS solutions.
Key Points:
Covers Supabase's history, features, advantages, and use cases.
Focuses on real-time functionality with technical explanations and code examples.
Compares Supabase to Firebase to highlight strengths and weaknesses.
Provides a brief getting started guide.
Formatted in Markdown and placed in src/content/docs/baas.

Product case study/supabase overview.md

---

src/content/docs/three-js/three-js-case-study.md

The following case study was a collaboration between Marius Kjesbu Bjeglerud, Weronika Karczmarczyk & Alex Storm Skoglund
Division of tasks:
Marius - Introduction & Brief History
Weronika - Main Features & Feature Table
Alex - Market Comparison & Getting started
Shared tasks - Conclusion & References

Adds case study:  three-js-case-study.md

---

src/content/docs/nosql/ScyllaDB/ScyllaDB-case-study-mar-ols.md

Adds an .md file with a case study on ScyllaDB.

Adds case study: ScyllaDB-case-study-mar-ols.md

---

src/content/docs/alpine/alpine-case-study.md

I have made a case study about Alpine.js  which is extremely lightweight, around 10kB in size, making it ideal for situations where it's needed to add interactivity to web pages without increasing load times significantly.

Adds case study: alpine-case-study.md

---

src/content/docs/cms/umbraco-case-study.md

Umbraco case study

---

src/content/docs/frameworks/Next.js/NextJs-as-backend.md

This PR explores using Next.js as a backend.

Next.js as a backend

---

src/content/docs/webdev-hosting/directAdmin/directAdmin_case_study.md

DirectAdmin case study

---

src/content/docs/databases/RavenDB/ravendb-case-study.md

This PR adds a case study on RavenDB, covering its features, history, strengths, weaknesses, market comparison, and a getting started guide.

RavenDB case study

---

astro.config.mjs
src/content/docs/squarespace/squarespace-case-study.md

This PR adds a case study exploring Squarespace and compares it to coding from scratch or using frameworks.

Squarespace case study

---

src/content/docs/microsoft/Azure/Azure-Virtualmachines-case-study.md

Azure Virtual machine topic has been done

azure-virtualmachines-case-study.md

---

src/content/docs/frameworks/CSS/tailwind-video-case-study.md

Here is my case study video, where I will be talking about Tailwind css.

tailwind-css video case study

---

src/content/docs/microsoft/Azure/Azure-Devops-Pipline.md

This report provides an overview of Azure DevOps Pipelines, covering its history, key features, applications, and strengths/weaknesses. It highlights its evolution from Visual Studio Team Services (VSTS), its versatility in supporting CI/CD workflows, and its seamless integration with various DevOps tools.
The document also compares Azure DevOps Pipelines with alternative tools like Jenkins and GitHub Actions, providing a comprehensive understanding of its role in modern software development workflows. A practical use case is included to demonstrate its effectiveness in automating CI/CD processes.

Azure devops piplines/case study

---

src/content/docs/devtools/Docker/docker-case-study-maksim.md

This pull request adds a detailed case study on Docker for our Assignment "DPA" (Development Platforms Assignment). 
You will see being covered
- History
- Architecture
- Main Features
- Strength
- Weakness
- Market comparison
- Security considerations
With the Includment of practical examples and references to official documentation.

Docker case study

---

src/content/docs/webdev-hosting/Vercel/vercel-case-study.md

Added a comprehensive case study of Vercel deployment platform, including:
- Platform overview and history
- Core features and capabilities
- Deployment workflow demonstration
- Comparison with competitors
- Strengths and limitations analysis

add vercel-case-study

---

src/content/docs/frameworks/React/case-study-react.md

This pull request includes a case study on React, a popular JavaScript library for building user interfaces. 
Introduction to React and its key features.
A brief history of React's development.
Added a detailed comparison table between React and Vue.js.
Provided a getting started section with code examples to help developers set up a React project using Vite.
Included references to reliable sources for further reading.
This case study will help new developers better understand React and its key features.
The "Getting Started" section will assist anyone looking to dive into React development and set up a project quickly.

React case study

---

src/content/docs/networking/cloudflare-case-study.md

Here is my case study which is about Cloudflare.

Adds case study: cloudflare-case-study.md

---

src/content/docs/webdev-hosting/Netlify/netlify-case-study-hø.md

This pull request adds a detailed case study on Netlify to the repository. It contains Netlify's history, features, advantages, disadvantages, and a comparison with Vercel. The goal is to provide a clear overview of the platform for developers and students learning about modern development platforms.

Netlify case study: netlify-case-study-hø.md

---

src/content/docs/replit/replit_case_study.md

Deep dive into replit, its use-case, features and advantagaes.

case_study_replit

---

src/content/docs/google/google-auth-case-study.md

This is a Google Authenticator case study. It provides information about authentication, Google Authenticator app, its features, how it works, pros and cons, and comparison to 2FAS.

Google auth case study

---

src/content/docs/ai-ml/tensorflow-ml-case-study.md

I noticed that there were already several case studies on TensorFlow, so I wanted to take a deeper dive into how TensorFlow uses machine learning. If unclear, my file name is tensorflow-ml-case-study.md.

Tensorflow case study

---

src/content/docs/xai/grok-case-study-victor-winsjansen.md

I've written a case study on the AI chatbot Grok developed by xAI. I used several online resources, including Grok itself.

Added Grok Case Study

---

src/content/docs/libraries/htmx-case-study.md

A detailed case study for the HTMX library.

Htmx case study

---

src/content/docs/shadcn-ui/product-case-study.md

This is a written case study on shadcn/ui, a modern component library for React built with Tailwind CSS.
**The case study includes:**
- Introduction and brief history of shadcn/ui
- Key features and usage
- Comparison with other UI libraries (Material UI, Chakra UI)
- Getting started instructions
- Use cases, strengths, and limitations
- Conclusion and references

Shadcn UI case study

---

src/content/docs/preact-case-study/preact-case-study.md

This pull request adds a comprehensive Preact case study to our documentation. The case study covers:
- Brief History of Preact
- Core Features and Benefits
- Detailed Comparison between Preact and React
- Insights and Key Takeaways from Student Perspectives

Preact Case Study: History, Features, Comparisons, and Student Insights

---

src/content/docs/databases/Fauna/fauna-case-study.md

This is a Noroff assignment, diving deeper into database models, more specifically **Fauna DB**. 
The objective of this assignment is to demonstrate the ability to **research development platform product offerings**, form opinions and relate this research to others via a written case study. 
- Added a new folder called 'Fauna' under src/databases. 
- Added a markdown file named 'fauna-case-study', adhering to the markdown file template provided by the assignment. 
- Filled in all the required sections and added a table of contents. 
- Added relevant research, product’s history, applications, strengths/weaknesses, and how it compares to other products in the market. 
- Added references. 
- Added pictures for better readability and material for further reading. 
Teacher review: @cnnrbrn

Fauna Case Study PR

---

src/content/docs/frameworks/React/case-study-react-noor807.md

- Added a comprehensive case study on React.js, covering its history, features, comparisons, and use cases.
- Included React vs. Vue vs. Angular comparison tables.
-  Detailed key React categories, variants, and frameworks like Next.js, Gatsby, and React Native.
- Provided real-world case studies from Netflix, Airbnb, Instagram, WhatsApp, Uber, Discord, and Facebook.
-  Covered setup guides, learning resources, and future trends in React.
-  Enhanced readability with tables, lists, and structured sections.

Case study react noor807.md

---

src/assets/ui-libraries/chakra-ui-case-study.md

This case study explores Chakra UI, a modular and accessible component library for React. It includes an overview of the framework, its key features, use cases, and how it compares to similar UI solutions in the React ecosystem. The study is written in markdown and placed under the appropriate directory in `src/content/docs/`.
Let me know if any formatting or placement needs adjusting!

Add Chakra UI Case Study

---

src/content/docs/deno/deno-case-study.md

This case study covers Deno, its security features, React compatibility, and comparisons with Node.js.

Deno Case Study Submission

---

src/content/docs/devtools/Jenkins/jenkins-case-study.md

This pull request includes my completed case study assignment for the Development Platforms course. The submission is provided as a single Markdown (.md) file and focuses on Jenkins as the chosen platform.
The case study explores Jenkins in depth, covering its background, core concepts, installation procedures, pipeline usage, and a comparative analysis with other modern CI/CD platforms.
- Overview of Jenkins and its role in CI/CD
- Key features and essential terminology
- Installation methods for Windows, macOS, and Linux
- Jenkins pipeline concepts with syntax examples
- Advantages and limitations of using Jenkins
- Comparative evaluation with alternative CI/CD tools
- Future relevance of Jenkins in 2024 and beyond
- Referenced sources and supplementary learning materials
- All …

Product case study

---

src/content/docs/baas/Appwrite/appwrite-case-study-kjahsin.md

(bricked battery and lost phone at the same time like a champ)
Sorry about this Jan Henning. I hope this is ok and works for the delivery.

added front matter and pushed from new github account 

---

src/content/docs/linux/linux-dev-platform-case-study.md

Case study on using Linux as a development platform. This report includes personal experience with Arch Linux and may lean towards my preferred distribution at times. The case reflects on both my personal insights and technical research.
This was a passion project, and I hope the topic aligns with the goal of the assignment.

Add case study: Linux as a development platform

---

src/content/docs/supabase/supabase-case-study.md

This PR adds a case study on Supabase to the development-platforms repository.
The markdown file is located under src/content/docs/supabase/ and includes the following:
•	Introduction to Supabase as a Backend-as-a-Service
•	Core features (PostgreSQL, auth, storage, realtime, etc.)
•	Strengths and limitations
•	Comparison with Firebase
•	Student-friendly explanation and usage overview
•	Sources and references
Author: Tonje Albertin Kristiansen

supabase case-study

---

src/content/docs/pocketbase/pocketbase-case-study.md

A case study where I look at PocketBase history, features and how it compares to other technologies in the market.

PocketBase case study.md

---

src/content/docs/case-study/supabase-case-study.md
src/content/docs/case-study/vite-hmr-case-study.md

Added a case study on Supabase for the Development Platforms course at Noroff.  
The case study includes an introduction, technical explanation, use cases, strengths and weaknesses, and a conclusion.

Add Supabase Case Study (Andreas Van der Spa)

---

src/content/docs/src/content/docs/product-case-study/supabase.md

A written case study about Supabase as a development platform. Created as part of the Development Platforms course assignment at Noroff.

Adds case study: supabase.md
